### PR TITLE
Add Sound and Vibration to Android and iOS notification

### PR DESCRIPTION
**Pull request by lorenzogiudici5**
The notification plays default sound and vibrates

### CODE REVIEW

**Comment by jamesmontemagno** [comment]
These should be configurable some way and off by default so it doesn't change functionality. Should most likely re-think the methods though.

**Comment by ionixjunior** [comment]
Nice! Exists a way in this plugin to automatic add vibration permission in Android?

When I tested vibration feature an exception appear because I don't added vibration permission on manifest.

**Comment by lorenzogiudici5** [comment]
@jamesmontemagno, referring to [your post](https://github.com/SimonSimCity/Xamarin-CrossDownloadManager/issues/19): adding android.permission.VIBRATE as an assembly attribute should work?

**Comment by cbyago** [comment]
when will these modifications be in the nuGet version?

**Review by zhubzy — APPROVED** [review]

**Comment by edsnider** [comment]
This plugin was moved to a dedicated repo in 2017. 
https://github.com/edsnider/LocalNotificationsPlugin

**Review by skycloudnest — COMMENTED** [review]
Great add it!!!!!!!!!!!!

**Pull request closed without merging**
