### PR TITLE
Android: Fixing issue where activity was being recreated for local no…

### PR DESCRIPTION
**Pull request by DottorPagliaccius**
@jamesmontemagno 

I use @gadzair's fix in both Show and OnReceive, without upgrading Support.V4 library as in #29.

### CODE REVIEW

**Comment by DottorPagliaccius** [comment]
I also add a way to specify custom Intent Action Filter; furthermore, I add notification id to Intent Extras (and some minor refactoring)

**Comment by edsnider** [comment]
Hi @DottorPagliaccius - we did some revamping to this repo and moved it to a dedicated repo (https://github.com/edsnider/LocalNotificationsPlugin) (see #37).  Would it be possible for you to pull latest from the new repo and re-submit this PR on the new repo?

**Comment by DottorPagliaccius** [comment]
@edsnider Done ;)

**Comment by edsnider** [comment]
Thanks!

**Comment by edsnider** [comment]
PR opened in new repo: https://github.com/edsnider/LocalNotificationsPlugin/pull/4

**Pull request closed without merging**
